### ISSUE TITLE
Adapter certaines routes pour afficher l'année scolaire sélectionnée dans l'URL (classes, validations, schoolings, ...)

### ISSUE THREAD

**Issue by tnicolas1** [betagouv/aplypro#1003]

**Comment by tnicolas1** [comment]
Ne plus afficher "Nous récupérons la liste de vos élèves." lorsqu'il n'y a pas d'élèves/de classes (/year/XXX/classes)

**Comment by gtournadre** [comment]
Concernant la saisie d'une PFMP individuelle : 
- Il faut bien rajouter l'année scolaire dans l'url car une PFMP est bien liée à une scolarité, donc une année scolaire. 
-
