### ISSUE TITLE
Dans le panneau des paiements, classer la liste des paiements bloqués, rejetés ou échoués par order alphabétique des nom et prénom de l'élève.

### ISSUE THREAD

**Issue by gtournadre** [betagouv/aplypro#1004]

**Comment by dsi-scol-acort-gvf** [comment]
Bonjour à toute l'équipe,

Pour rebondir sur cette proposition, toujours concernant la liste des paiements échoués : est-il prévu d'ajouter une simple fonctionnalité de tri et / ou de filtre concernant les différentes colonnes ?

Quelque chose de similaire à ÉduConnect, par exemple :

![Gestion des élèves - ÉduConnect](https://github.com/betagouv/aplypro/assets/174694543/537bf226-68de-44f3-93cd-f88639c7cec5)

En effet, il arrive que ce tableau contienne plusieurs dizaines de lignes (dont des doublons) et une recherche approfondie impose de copier-coller cela dans un tableur, de l'éditer, puis d'y appliquer des filtres et tris.

Merci,
