### ISSUE TITLE
Revoir URL de la page de gestion d'un élève

### ISSUE THREAD

**Issue by gtournadre** [betagouv/aplypro#1011]
Vu le 2 juillet 2024 : 
- A terme, la page de gestion de l'élève **ne doit pas dépendre de l'année scolaire ni de la classe**. 
Note : on accède au panneau de gestion de l'élève à partir de la liste des classe DE L'ANNEE SCOLAIRE SELECTIONNEE.  A terme, le mieux serait une zone de texte "Rechercher" dans laquelle on tape le nom de l'élève et qui nous renvoie sur l'écran de gestion de l'élèves (coordonnées bancaires, PFMPs par scolarité). 
- Au lieu d'avoir une URL de la forme http://<server>/classes/x/Students/xxx : http://<server>/Students/xxx
- Même comportement à mettre en place pour la fonction modifier les coordonnées bancaires
- On retrouve toutes les classes que l'élève a fréquenté dans l'établissement par ordre chronologique (le plus récent en haut)
- On retrouve pour chaque classe toutes les PFMP saisie pour pour l'élève. 
- On retrouve aussi l'accès à la gestion des coordonnées bancaires. 
- Ajouter l'année scolaire dans l'intitulé de la classe
- La page des PFMPs est en lecture seule, sauf pour les classes de l'établissement sélectionné dans APLYPro

![Image](https://github.com/betagouv/aplypro/assets/160624490/8ef4c780-83ed-48ae-a088-a3afb06b086e)

**Comment by gtournadre** [comment]
Pour 1 Elève : 
1. Afficher les coordonnées bancaires
2. Boucle sur les scolarités
3. Pour chaque scolarité indiquer classe.label et mef.label
4. Boucle sur les PFMPs de la scolarité
5. Pour chaque PFMP afficher date début date de fin et nombre de jours

**Comment by tnicolas1** [comment]
Gérer également les droits d'édition du RIB d'un élève : https://github.com/betagouv/aplypro/issues/1041
