### ISSUE TITLE
Les PFMPs doivent être verrouillées dès lors qu'elles ont été vues par l'ASP

### ISSUE THREAD

**Issue by freesteph** [betagouv/aplypro#1013]
À l'heure actuelle on empêche la modification/suppression des PFMPs si : 

https://github.com/betagouv/aplypro/blob/9d50d8e7cb6be7a7a3bd105577a8677414d6cd19/app/models/pfmp.rb#L97-L99

Comme `ongoing?` inclue les états 

https://github.com/betagouv/aplypro/blob/9d50d8e7cb6be7a7a3bd105577a8677414d6cd19/app/models/asp/payment_request_state_machine.rb#L16

Cela implique qu'on peut supprimer une PFMP qui a eu un paiement rejeté (`rejected`). Donc dans le scénario – et on sait d'expérience que ça arrive – où les personnels suppriment puis recréent une PFMP pour essayer de redéclencher/retenter le paiement :  

1. une PFMP X est envoyé avec le numéro administratif ABC ; 
2. l'ASP rejette le dossier ABC pour une raison quelconque ;
3. un personnel supprime et recréé la PFMP pour essayer de débloquer la situation ;
4. l'ASP reçoit une demande d'ouverture de dossier avec le même numéro administratif ABC puisque qu'aucun des éléments qui le constitue n'a changé depuis (entre PFMPs d'une même scolarité c'est l'index de la PFMP qui les distingue i.e PFMP 1, PFMP 2, PFMP 3) ;
5. et le rejette avec "le numéro administratif ABC n'est pas unique".

Il faudrait encoder la logique "une PFMP ne peut pas être supprimée si elle a été vue par l'ASP".

**Comment by pskl** [comment]
Oui c'est une bonne suggestion, merci Stéphane
