### ISSUE TITLE
Ajouter le code commune des Establishments

### ISSUE THREAD

**Issue by gtournadre** [betagouv/aplypro#1036]
Afin de pouvoir payer les élèves résidents à l'étranger (#997 ), il est convenu d'envoyer à l'ASP le code commune et le code postal de leur établissement scolaire. 
Pour cela il faut récupérer le champs "code_commune" de l'API https:;/data.education.gouv.fr et le stocker en base de données.

**Comment by pskl** [comment]
`EstablishmentApi.fetch!(uai`
