### ISSUE TITLE
Amélioration de la page Paiements

### ISSUE THREAD

**Issue by gtournadre** [betagouv/aplypro#1065]
La page paiements actuels permet : 
- De valider des PFMP complètes pour les envoyer en paiement
- De consulter les demandes de paiement non abouties (incomplete [bloquées par sorties d'APLyPro]; rejected [demande rejetée par SERAPIS] et unpaid [paiement échoué : invalidé par l'agence comptable de l'ASP]). 

En tant que chef d'établissement je veux pouvoir suivre ici TOUTES les PFMPS, qu'elle soient pending, complete ou validated, et suivre aussi leur état de mise en paiement. 

Cette page est à renommer "PFMPs et paiements". Elle est liée à l'année scolaire. 
Elle contient la liste des classes, et pour chaque classe un tableau des élèves. Les colonnes : 
- Elève : Prénom NOM (idélaement un lien sur Prénom NOM qui envoie vers la page élève)
- Coord. bancaires : Saisies ou Absentes
- PFMPs : liste des PFMPs saisies pour l'élève (une ligne par PFMP, date début - date fin)
- Nb Jours : Nb de jours saisies pour la PFMP ( vide ou tiret si par renseigné)
- Mise en paiement :  état de la mise en paiement comme déjà existant (En attente pour pending ou ready, Bloqué pour incomplete, En traitement pour send ou integrated,, rejeté pour rejected, Paiement envoyé pour paid et paiement échoué pour unpaid). 
- Valider : un colonne vide pour les PFMPs qui sont déjà en cours de paiement et qui contient un lien pour valider une PFMP et l'envoyer en paiement. 

en bas de ce tableau garder la liste des paiement non aboutis car c'est eux qui vont susciter le plus d'interrogations.

**Comment by gtournadre** [comment]
[Page_PFMP_PAIEMENTS.pdf](https://github.com/user-attachments/files/16391583/Page_PFMP_PAIEMENTS.pdf)

**Comment by tnicolas1** [comment]
@gtournadre Est-ce que le travail qui a déjà été réalisé correspond aux attentes de cette carte ? (https://github.com/betagouv/aplypro/pull/1125)
