### ISSUE TITLE
Mettre en place la gestion des indus

### ISSUE THREAD

**Issue by gtournadre** [betagouv/aplypro#1066]
La gestion des indus intervient uniquement sur les Payment Requests dont l'état est "paid". Il faut pouvoir modifier la PFMP alors qu'elle est normalement vérouillée puisque payée. voici mes Idées :  

1. Ajouter un état à pfmp_transitions par exemple "rectified". Cet état doit permettre de modifier la PFMP : montant (obligatoire), nombre de jours, dates etc.... Si le nombre de jours change, il est possible de calculer automatiquement le nouveau montant de la PFMP. 
**Il faut ajouter des informations sur l'adresse de l'élève, 2 champs correspondant à adresse ligne 1 et adresse ligne 2 préremplies avec les données présente dans APLyPro (pour certains élèves, elles n'y sont pas)**

Le formulaire doit permettre d'alimenter les balises suivantes du fichier XML envoyé à l'ASP: 
Ligne 1  ``<POINTREMISE> ``,
Ligne 2  ``<CPLTDISTRIBUTION> ``,
code postal (rempli automatiquement à partir d'APLyPro)  ``<CODEPOSTALCEDEX> ``,

Les balises ``<CODEINSEEPAYS> `` et  ``<CODECOMINSEE>  ``seront remplies directement par APLyPro

2. Permettre de revenir à l'état validated dans pfmp_transitions afin de créer une nouvelle demande de paiement sur la PFMP, adapter le job de génération du XML  à envoyer à l'ASP  pour envoyer TOUTE l'adresse de l'individu renseignée ou validée par l'établissement. 

3. adapter le job d'intégration des retours ASP, pour intégrer les fichiers potentiels : 
Question : existe-t-il un état "integrated". 
renvoi_paiement_DISPO1_20160502.xml (2 état possibles : "PAYE" ou "INVALIDE")
renvoi_ordrereversement_DISPO1_20111110.xml (2 état possibles : "EMIS" ou "INVALIDE")
(le nom pour APLyPro est spécifique)

Question en suspend : est-ce qu'il faut mapper EMIS sur PAID? cela serai un gain important sur la machine à état.

**Comment by pskl** [comment]
On fait que des montants positifs, on envoit un nouveau paiement à l'ASP avec la même triplette. SERAPIS détecte le changement automatiquement.

**Comment by gtournadre** [comment]
Pour l'adresse, il peut-être préférable de la stocker au niveau du Student. Pour faire rentrer dans les balises Adresses de l'ASP : 
On se servirai des lignes 1 et 2 pour alimenter les balises XML <POINTREMISE> et <CPLTDISTRIBUTION>. Côté interface APLyPro, ces champs pourront être pré-remplis à partir du contenu APLyPro, bien faire attention à ne pas dépasser 38 caractères.

**Comment by pskl** [comment]
Estimation: 2 semaines

**Comment by pskl** [comment]
```
<LISTEOR>
	<ORDREREVERSEMENT>
		Informations sur l’ordre de reversement 1
	</ORDREREVERSEMENT>

	<ORDREREVERSEMENT>
		Informations sur l’ordre de reversement 2
	</ORDREREVERSEMENT>

	<ORDREREVERSEMENT>
		Informations sur l’ordre de reversement 3
	</ORDREREVERSEMENT>
</LISTEOR>
```

```
<ORDREREVERSEMENT>
		Info générale de l’ordre de reversement
		<LISTEPRESTADOSS>
			<PRESTADOSS>
				Info générale sur la prestation dossier
				<LISTEELEMENTPAIEMENT>
					<ELEMENTPAIEMENT>
						info générale elts paiement
						<LISTEVERSEMENT>
							<VERSEMENT>
				  				info générale versement
								<LISTEFINANCEMENT>
									<FINANCEMENT>
										info financement 
									</FINANCEMENT>
								</LISTEFINANCEMENT>
							</VERSEMENT>
						</LISTEVERSEMENT>
					</ELEMENTPAIEMENT>
				</LISTEELEMENTPAIEMENT>
			</PRESTADOSS>
		</LISTEPRESTADOSS>
	</ORDREREVERSEMENT>
```
