### ISSUE TITLE
Evolution des appels et mappers de SYGNE

### ISSUE THREAD

**Issue by gtournadre** [betagouv/aplypro#1086]
2 Appels sont faits à SYGNE depuis APLyPro : 
- 1 appel à la liste des élèves d'un établissement pour récupérer la version des classes
  il faut adapter cet appel en filtrant sur les scolaires uniquement, les apprentis ne doivent pas apparaître dans APLyPro. 

- 1 appel unitaire aux détails de l'élève qui permet de récupérer l'adresse, la commune de naissance etc...
  Il faut adapter le Mapper : dans SYGNE on a adresse_ligne1, adresse_ligne2, adresse_ligne3, adresse_ligne. Dans APLyPro, on a que 2 lignes d'adresse. Par défaut le mapper place fait correspondre ligne 1 et ligne 2 mais dans Sygne, Ligne 1 et 2 ne sont pas toujours renseignées. Il faudrait donc tester si ligne1 de sygne est valorisé, si null tester ligne 2 etc, pour remplir ligne 1 et ligne 2 d'aplypro avec des valeurs. ,

**Comment by tnicolas1** [comment]
Remplace https://github.com/betagouv/aplypro/issues/306

**Comment by gtournadre** [comment]
Ajouter aussi une gestion des changement d'état civil
#1087
