### ISSUE TITLE
Récupérer les précédentes coordonnées bancaires

### ISSUE THREAD

**Issue by ac-clermont-dylan** [betagouv/aplypro#1105]
**En tant que** personnel d'établissement

**Je veux** pouvoir récupérer les coordonnées bancaires saisies par l'établissement précédent

**Afin de** gagner du temps lors de la saisie des RIBs

**Comment by pskl** [comment]
Pas forcément une bonne idée au niveau vie privée je crois.

**Comment by tnicolas1** [comment]
Annulation de la fonctionnalité
