### ISSUE TITLE
Interface pour marquer les élèves non admis pour les directeurs

### ISSUE THREAD

**Issue by pskl** [betagouv/aplypro#1110]
Les directeurs doivent pouvoir marquer un élève comme jamais admis au sein de la classe.

-> Ajouter un bouton pour qui update un champ `removed_at` sur l'étudiant qui contient le timestamp du marquage

**Comment by gtournadre** [comment]
Donner cette possibilité uniquement sur les élèves qui ont deux ou plus scolarités avec des dates qui se chevauchent

**Comment by gtournadre** [comment]
Cette fonctionnalité doit être reversible.
