### ISSUE TITLE
Adapter Mapper FREGATA

### ISSUE THREAD

**Issue by tnicolas1** [betagouv/aplypro#1131]
Message MASA
Bonjour,
Le filtre permettant de sélectionner les apprenants, et en l'occurrence de récupérer uniquement les élèves, a été déployé en environnement de qualification. Pour cela, il suffit d'ajouter &idStatutApprenant=2 à la suite de l'appel.

@tnicolas1 si tu peux regarder pour modifier l'appel à FREGATA? 
MErci

**Comment by tnicolas1** [comment]
L'option 'idStatutApprenant=2' dans POSTMAN ne semble pas changer le nombre de retours (testé sur une dizaine d'établissement)

**Comment by thibault** [comment]
@tnicolas1 Je crois que tu as pingué le mauvais Thibault :D

**Comment by ac-clermont-dylan** [comment]
![image](https://github.com/user-attachments/assets/7c3117bd-89f7-47d9-a9db-09c0c98dbbc2)

**Comment by ac-clermont-dylan** [comment]
![image](https://github.com/user-attachments/assets/410852b8-26d5-419a-91ef-4112fea5fe12)
