### ISSUE TITLE
Intégration des collèges de Mayotte

### ISSUE THREAD

**Issue by tnicolas1** [betagouv/aplypro#1156]
Certains collèges proposent des CAP, donc ils ont un certain nombre d'élèves éligibles. 
Est-ce qu'il vaut mieux autoriser le type d'objets CLG ou est-ce qu'il vaut mieux ajouter uniquement les collèges concernés? 

Il existe un mécanisme d'exclusion, peut-on ajouter un mécanisme d'inclusion?

**Comment by gtournadre** [comment]
5 collèges de Mayotte proposent des formations CAP éligibles à l'allocation pour les Lycéens Professionnels.
Il n'est pas souhaitable d'autoriser les établissements de type collège dans APLyPro, afin de ne pas polluer la base de données avec des établissements qui n'ont rien à y faire.
Le plus simple est d'ajouter manuellement les établissements, autoriser manuellement les responsable d'établissements à s'y connecter, et ensuite de s'assurer :

    Que les MEF concernés sont bien dans le référentiel des MEFS pour les années scolaires concernés.
    Que l'appel à Sygne est autorisé pour les établissements en question.
