### ISSUE TITLE
Créer un script de fermeture des scolarités 2023 / 2024

### ISSUE THREAD

**Issue by gtournadre** [betagouv/aplypro#1160]
Une fois la nouvelle année 2024 / 2025 créée, il faudra fermer toutes les scolarités 2023 - 2024 qui sont encore ouverte. Script à créer : 
Pour toutes les scolarités dont la classe a un school_year à 1 ET dont la date de fin est null
   Si Académie est Réunion ou Mayotte : Schoolings.end_date = "2024-08-18"
   Si autre académie : Schoolings.end_date = "2024-09-01"

**Comment by gtournadre** [comment]
A jouer d'abord sur Staging

**Comment by pskl** [comment]
Tout simplement:
```rb
Establishment.all.each do |e|
  e.schoolings.update_all(end_date: e.school_year_range.first)
end
```
