### ISSUE TITLE
[BUG] Déscolarisation en masse d'élève la nuit sans explication

### ISSUE THREAD

**Issue by DiffusionAplyPro** [betagouv/aplypro#1201]
Bonjour,

J'ai un établissement qui constate que de nombreux élèves sont sortis de classe.

Après analyse, rien n'explique cela.

Etab ID : 1550

317 élèves déscolarisés, pas de doublon de classe et pas de nouvelle scolarité créée ailleurs.

Toutes les sco ont été mises à jour le 04/11/2024 entre 23:27:35 et 04/11/2024 23:27:58

Échantillon de student_id :
355063
678318
319615
319609
319594
319593
319619
319617
319598
319606 

L'interrogation de l'API Sygne montre bien que les élèves sont scolarisés (pas de date de fin de sco).

Mickael

https://sesam.in.orion.education.fr/sesam/view.php?id=511416

**Comment by DiffusionAplyPro** [comment]
seuls les élèves nouveaux entrants sont correctement renseignés, les élèves déjà présents dans les établissements apparaissent "sortis de la classe"

**Comment by pskl** [comment]
Tous les ids de scolarités mentionnées correspondent à des classes de 2023-2024 donc c'est normal qu'elles soient fermées. 

Maintenant pourquoi est-ce qu'ils n'apparaissent pas dans de nouvelles classes? C'est possiblement un problème au niveau des établissements?
