### ISSUE TITLE
[BUG] Impossibilité de changer un RIB

### ISSUE THREAD

**Issue by DiffusionAplyPro** [betagouv/aplypro#1203]
Bonjour,

J'ai une demande pour un changement de owner de RIB.
L'élève a une seule PFMP en incomplète (pas d'autres PFMP en cours d'envoi à l'ASP).

J'ai le message suivant en voulant passer sur le RIB de l'élève au lieu du tiers : 
![image](https://github.com/user-attachments/assets/7f63b132-2078-4650-b18a-8a9a48aa9502)

https://aplypro.beta.gouv.fr/students/53895/ribs/211939/edit

Mickael

https://sesam.in.orion.education.fr/sesam/view.php?id=511443

**Comment by ac-dylan** [comment]
Ticket Sésam mis à jour, on a 4 cas.

**Comment by gtournadre** [comment]
#1230
