### ISSUE TITLE
[EVO] Bloquer la saisie du nombre de jour d'une PFMP si elle n'est pas terminée

### ISSUE THREAD

**Issue by DiffusionAplyPro** [betagouv/aplypro#1227]
Bonjour,

Un établissement vient de saisir, valider et envoyer en paiement 47 PFMP qui doivent se dérouler en janvier/février 2025.
![image](https://github.com/user-attachments/assets/5ee7673a-fcac-434e-9537-ac32c30aaac6)
https://aplypro.beta.gouv.fr/year/2024/classes/51710/schoolings/861385/pfmps/1734088
Il n'est pas normal que cela puisse se produire.
Les process sont que la saisie du nombre de jours doit se faire à partir de l'attestation de fin de stage qui ne peut être délivrée qu'en fin de stage soit après la date de fin dudit stage.

Il serait bon de mettre un contrôle dessus pour éviter que d'autres cas identiques n'arrivent.

Mickael
https://sesam.in.orion.education.fr/sesam/view.php?id=513006

**Comment by gtournadre** [comment]
La solution la plus simple pour pallier à ce problème est au moins de modifier la validator : si endDate de la PFMP est supérieur à current_date alors on marque la Payment_request incomplete car PFMP invlaid
