### ISSUE TITLE
Aiguiller les utilisateurs MASA vers leur gestionnaire COLENTAGRI

### ISSUE THREAD

**Issue by freesteph** [betagouv/aplypro#124]
Certains personnels du MASA essaient de se connecter mais leur vecteur d'identité retour ne contient pas les bons attributs (ou parfois pas d'attributs). Les donnés qui nous sont retournées viennent de l'annuaire SAPIA qui est enrichi (i.e `FrEduRne` + `FrEduRneResp` etc) avec un logiciel COLENTAGRI.

Pour pouvoir corriger leur données, il faudrait leur afficher un message d'erreur qui leur explique ça, et qui les dirige vers la bonne instance capable de corriger ces donnés : 

* un gestionnaire COLENTAGRI au sein de leur établissement ;
* les Délégués Régionaux aux Technologies de l'Information et de la Communication (DRTIC) ;
* le support CNERTA.

**Comment by JeSuisUnCaillou** [comment]
Peut-on considérer que l'amélioration du message d'erreur [ici](https://github.com/betagouv/aplypro/pull/139/commits/731c801f5367fb1005eb06ba0b2da05a3e2d38f9) a suffit ?

**Comment by freesteph** [comment]
Oui, on affinera si besoin merci pour le fix.
