### ISSUE TITLE
Erreur "we're sorry, but something went wrong."

### ISSUE THREAD

**Issue by ac-dylan** [betagouv/aplypro#1283]
A la connexion de l'établissement 0940743X l'erreur "we're sorry, but something went wrong." apparait.

![Image](https://github.com/user-attachments/assets/1192a0ef-a4be-4434-806d-3af7655819ba)

https://sesam.in.orion.education.fr/sesam/view.php?id=515150

**Comment by gtournadre** [comment]
Effectivement, on dirait que cet établissement fait planter la connexion....

**Comment by gtournadre** [comment]
LE confirmed_director_id pointe sur un user qui n'existe plus.....
