### ISSUE TITLE
Problème de versionning GIT et application

### ISSUE THREAD

**Issue by DiffusionAplyPro** [betagouv/aplypro#157]
Bonjour,

En mettant à jour notre outil de ticketing avec les vrsion APLyPro disponibles sur GIT, je me rend compte d'un décalage.
GIT v1.1.8, appli v1.1.9.

![Screenshot 2023-11-15 at 10-30-07 betagouv_aplypro Aplypro - Allocation pour les lycéens pro](https://github.com/betagouv/aplypro/assets/150439570/ecdff964-3060-478c-9147-971bf30afa35)

![Screenshot 2023-11-15 at 10-30-15 - APLyPro](https://github.com/betagouv/aplypro/assets/150439570/1e8d468b-bcc8-450b-ad72-671215350748)

**Comment by freesteph** [comment]
Corrigé, merci beaucoup !
