### ISSUE TITLE
Liste des mails académiques autorisés, il n'y a pas ac-wf.wf pour Wallis et futuna

### ISSUE THREAD

**Issue by DiffusionAplyPro** [betagouv/aplypro#174]
Un oubli dans la liste que je vous ai transmise.

![image](https://github.com/betagouv/aplypro/assets/150439570/480df674-d2ab-436a-82b1-e54070bf8ff1)

**Comment by JeSuisUnCaillou** [comment]
Parmi les 85 users qui ont un email en dehors des domaines autorisés, voici les stats par domaine :

eu-asso.fr : 1
cneap.fr : 49
rochefeuille.fr : 2
besancon.cneap.fr : 1
apprentis-auteuil.org : 2
briace.org : 1
ac-cned.fr : 1
ac-lyon.fr-existedejauid-0693134g : 1
jeannedelanoue.com : 1
ac-hn01.fr : 1
st-exupery.org : 2
hovia.org : 1
lycee-schattenmann.org : 1
ac-caen.fr : 4
ehproville.com : 1
saintmartin-machecoul.fr : 1
paris.fr : 1
institutdegenech.fr : 1
lyppra.cneap.fr : 1
orange.fr : 1
campus-pouille.com : 1
lea-cfi.fr : 2
exemple.com : 1
lyceelesvergers.com : 1
pommerit.fr : 1
dalzon.com : 1
rochefeuillle.fr : 1
ac-noumea.nc : 1
kerplouz.com : 1
lyceejberiau.fr : 1
