### ISSUE TITLE
Bouton pour changer d'établissement si un personnel gère APlyPro dans plusieurs établissements

### ISSUE THREAD

**Issue by DiffusionAplyPro** [betagouv/aplypro#180]
Bonjour,

Un utilisateur souhaiterait un bouton changer d'établissement si un personnel gère APlyPro dans plusieurs établissements

![image](https://github.com/betagouv/aplypro/assets/150439570/ebb36afb-afb4-4452-9e0f-1d9acd593f7f)

**Comment by JeSuisUnCaillou** [comment]
La demande d'évolution est pertinente. En attendant l'implémentation, vous pouvez répondre aux utilisateurs qu'ils peuvent se déconnecter-reconnecter pour ré-obtenir le choix d'établissement après leur reconnexion.

**Comment by JeSuisUnCaillou** [comment]
Closed by https://github.com/betagouv/aplypro/pull/324
