### ISSUE TITLE
SEP sans élèves scolarisé dans APLyPro

### ISSUE THREAD

**Issue by DiffusionAplyPro** [betagouv/aplypro#181]
Un utilisateur nous remonte le fait qu'il a accès à la SEP de son établissement et qu'aucun élève n'est scolarisé dans siècle sur cette dernière. Tous les élèves sont scolarisé sans le lycée général.

![image](https://github.com/betagouv/aplypro/assets/150439570/f628114d-e60a-4a74-8fdd-cc360288d356)

**Comment by freesteph** [comment]
Peut-on avoir l'UAI de l'établissement en question ?
