### ISSUE TITLE
mauvais nom de chef d'établissement dans les DA de certains établissements

### ISSUE THREAD

**Issue by DiffusionAplyPro** [betagouv/aplypro#184]
L'établissement : 0080008R - LPO LYC METIER FRANCOIS BAZIN CHARLEVILLE-MEZIERES rapporte le problème suivant :

Lors de l'édition des conventions dans l'application, les conventions indiquent comme chef d'établissement M. Marc G. Or le chef d'établissement actuel est M. Jean-Marie A.

Comment pouvons-nous corriger le problème ? Quelle est la source d'aplypro pour le chef d'établissement ?

**Comment by freesteph** [comment]
APLyPro ne peut pas faire la différence entre le chef d'établissement et son adjoint, parce que les guichets d'authentification ne les distinguent pas eux-même.

Nous pouvons préciser dans le document "le chef d'établissement ou son adjoint" mais je ne sais pas vraiment comment adresser ce problème autrement.

@JeSuisUnCaillou une suggestion ?

**Comment by JeSuisUnCaillou** [comment]
On choisit un arbitrairement le premier utilisateur qui s'est connecté parmi tous ceux qui ont un rôle `DIR` dans leur `FrEduFonctAdm`. Les chefs d'établissements et leurs adjoints rentrent tous sans distinction dans ce cadre.

Ce qu'on met dans les décisions d'attribution c'est : "Marc Machin, représentant légal de l’établissement d’enseignement Lycée Truc". Ca pourraît être valable pour un adjoint, je ne sais pas. Je remonte la question au métier.

Sinon peut-être y a-t-il un moyen d'obtenir l'info sur l'API  https://data.education.gouv.fr/api ?

**Comment by JeSuisUnCaillou** [comment]
Réponse du métier :

> Il faut impérativement que ce soit le chef d’établissement. C’est lui qui est ordonnateur. C’est donc lui qui a la responsabilité des dépenses publiques qu’il engage. C’est un rôle qu’il ne peut pas déléguer à un adjoint.

**Comment by JeSuisUnCaillou** [comment]
Note : regarder du côté de DEMACT, AFFENET ou DELEG-CE pour obtenir la donnée du nom de chef d'établissement.

**Comment by JeSuisUnCaillou** [comment]
Exemple : sur l’établissement 0130001F

En utilisant l'API responsable_uo vous allez avoir le numéro du poste du chef d'établissement :

https://pr-api.omogen.in.phm.education.gouv.fr/mesirh/rsp/api/externe/responsable_uo?idFonctionnel=0130001F&dateObservation=2023-12-04
{"idFonctionnel":"0130001F","poste":{"idPoste":"19099","dateDebut":"1989-09-01","dateFin":"9999-12-31"}}

 
Il faudra alors faire un appel au RUA pour avoir le nom de l'agent (le RUA nécessite une API-key que nous pourrons vous fournir)

https://pr-api.omogen.in.phm.education.gouv.fr/mesirh/rua/v2/occupations-poste?poste=19099
```json
[
  {
    "idSource": "1276768",
    "typeNSI": "S",
    "nir": "189043155550370",
    "numen": "16E1288502WWL",
    "nomUsage": "EL YAGOUBI",
    "prenom": "SAMI",
    "affectationOperationnelle": {
      "identifiantUS": "0130001F",
      "identifiantPoste": "19099",
      "identifiantUSAA": "0130001F",
      "nature": "NORMA",
      "dateDebut": "2023-09-01",
      "indicateurAffectPrincipale": true,
      "pourcentAffectPoste": 100,
      "equivalentsTP": [
        {
          "equivalentTP": 1
        }
      ],
      "emploiType": "MPC08"
    }
  }
]
```

**Comment by JeSuisUnCaillou** [comment]
Réglé applicativement en incitant les adjoints à ne pas générer les documents si ils ne sont pas le responsable légal.
Fait ici https://github.com/betagouv/aplypro/issues/277
