### ISSUE TITLE
Des élèves ont disparu de l'affichage d'une classe

### ISSUE THREAD

**Issue by DiffusionAplyPro** [betagouv/aplypro#204]
Nous sommes contactés par les académies de Poitiers et de Besançon pour ce qui semble être le problème similaire.
![image](https://github.com/betagouv/aplypro/assets/150439570/21a404df-809d-414e-8588-731f120458a0)
Avec une mise à jour aujourd’hui : 
 
![image](https://github.com/betagouv/aplypro/assets/150439570/a67d03b4-54ae-499d-b8ae-5695d1382f9e)

Le compteur des décisions d’attribution est passé de 50/151à 42/128 (23 élèves ont « disparu » mais sont bien toujours dans la base APLYPRO.
En complément nous avons la note de Besançon
 
![image](https://github.com/betagouv/aplypro/assets/150439570/4bb12ef3-a7bb-47a0-b842-e9915b0147aa)

Il semble qu'une coupure réseau ait provoqué le problème/blocage

**Comment by JeSuisUnCaillou** [comment]
Pour les établissements bloqués sur la génération des DA, c'était dû à [cette issue](https://github.com/betagouv/aplypro/issues/178) désormais réglée.
On doit passer en mode maintenance pour débloquer les établissements dans le cas du 0861113T, je décrirait l'avancée de ce processus dans [cette issue](https://github.com/betagouv/aplypro/issues/207)

**Comment by JeSuisUnCaillou** [comment]
Pour les numbres d'étudiants qui changent, c'est probablement dû à une évolution qu'on a passé hier. 
On n'avait pas une bonne gestion des mouvements d'élèves avant, et l[es élèves partis étaient encore affichés dans la classe](https://github.com/betagouv/aplypro/issues/142).
On fait une mise à jour pour mieux les gérer. A priori maintenant, APLyPro reflète exactement la liste des élèves que renvoie SYGNE. 
Si ce n'est pas le cas pour un établissement, nous aimerions avoir le détail de quels élèves manquent dans quelle classe exactement, pour pouvoir investiguer.

**Comment by JeSuisUnCaillou** [comment]
On a trouvé une erreur de gestion des scolarité dans notre code. On va déployer [un fix](https://github.com/betagouv/aplypro/commit/d01c71920867a1274b2c6fb570faba6bc7776389)

**Comment by DiffusionAplyPro** [comment]
Bonjour
Le problème persiste cet après-midi.
![image](https://github.com/betagouv/aplypro/assets/150439570/2aea46a3-eca3-421a-86e1-f18bb5ad87e6)

**Comment by DiffusionAplyPro** [comment]
Bonjour,

Nous avons encore des soucis sur la génération.

Cordialement,

Mickael
