### ISSUE TITLE
Changement de classe élève qui a déjà une décision d'attribution

### ISSUE THREAD

**Issue by DiffusionAplyPro** [betagouv/aplypro#206]
établissement 0350807M - PR LP NOTRE DAME - SAINT-MEEN-LE-GRAND qui a une élève qui a changé de classe, ce qui a bien été pris en compte sous APLyPro.

En revanche, sur la décision d'attribution, c'est toujours l'ancienne classe qui est affichée. Que peut-on faire?
Me contacter pour les détails élèves

**Comment by JeSuisUnCaillou** [comment]
Nous devons implémenter la possibilité pour un chef d'établissement de re-générer la DA d'un élève.

**Comment by JeSuisUnCaillou** [comment]
Besoin d'un établissement avec exemple concret.

**Comment by JeSuisUnCaillou** [comment]
Plus besoin car on a désormais une DA par scolarités
