### ISSUE TITLE
suppression d'élève

### ISSUE THREAD

**Issue by DiffusionAplyPro** [betagouv/aplypro#209]
la question suivante a été soumise comment faire pour supprimer un élève qui n'est plus scolarisé?

**Comment by JeSuisUnCaillou** [comment]
Il faut le mettre à jour dans la base d'élèves, et APLyPro devrait recevoir la mise à jour.

**Comment by DiffusionAplyPro** [comment]
Bonjour
merci pour l'info, on est d'accord que la mise à jour doit être faite dans sygne?
merci
