### ISSUE TITLE
élève qui n'apparaît pas 

### ISSUE THREAD

**Issue by DiffusionAplyPro** [betagouv/aplypro#215]
Dans le 0261397C (LPO LYCEE DES METIERS HENRI LAUREN) un élève n'apparaît pas.
Entre le 4 et le 8 sept il était dans un autre établissement.
Il apparaît bien dans la base Aplypro dans l'établissement 0261397C .
Je vous transmets les info élève par mail

**Comment by freesteph** [comment]
C'est bon, résolu avec https://github.com/betagouv/aplypro/issues/204.

>   Il apparaît bien dans la base Aplypro dans l'établissement 0261397C .

c'est à dire ?

**Comment by DiffusionAplyPro** [comment]
je le trouve bien dans la base de données dans la table students.
