### ISSUE TITLE
erreur à la saisie d'une PFMP

### ISSUE THREAD

**Issue by DiffusionAplyPro** [betagouv/aplypro#216]
Dans le 0130056R, pour un élève donne (détails par mail), une saisie collective a été réalisée mais elle ne s'applique pas sur un élève.
Un message d'erreur s'affiche quand on va dans une saisie indiv

**Comment by freesteph** [comment]
Cet élève ne devrait pas/plus apparaître, pouvez-vous les relancer sur le sujet ? j'enlève les captures d'écran par souci de confidentialité.

**Comment by DiffusionAplyPro** [comment]
Pourquoi est-ce que cet élève ne devrait plus apparaître?
Merci

**Comment by freesteph** [comment]
encore un bug de schooling fermé, c'est corrigé. Son schooling avait été fermé ce qui empêchait la saisie.
