### ISSUE TITLE
nb de jours incorrect

### ISSUE THREAD

**Issue by DiffusionAplyPro** [betagouv/aplypro#217]
dans le 0711729U, une période de stage de 5 semaines a été saisie pour la classe TMMV, du 20/11/2023 au 23/12/2023.
Cela fait 5 semaines donc 25 jours de stage, mais aplypro affiche 17 jours.
![nb jours aplypro](https://github.com/betagouv/aplypro/assets/150439570/f7aa0f8d-05db-4844-be77-357783b65b2b)

**Comment by freesteph** [comment]
Je ne comprends pas la capture d'écran ?

Pour ce qui est des dates, aucun calcul n'est effectué sur les dates, on le précise dans le formulaire d'une PFMP individuelle :

>     Les dates saisies doivent correspondre à celles qui figurent dans la convention de stage.
>  Le nombre de jours doit correspondre à celui qui figure dans l'attestation de fin de stage.

Il faudrait sûrement le préciser sur la saisie de masse aussi.

**Comment by DiffusionAplyPro** [comment]
Vous pouvez clôturer et supprimer cette issue (confidentialité)

Il y a eu confusion entre nb de PFMP et nombre de jours de stage...
