### ISSUE TITLE
Empêcher la validation de PFMP si pas de DA ou pas de RIB pour l'élève

### ISSUE THREAD

**Issue by JeSuisUnCaillou** [betagouv/aplypro#255]
- Rendre visible les élèves à qui il manque des RIBs ou des DA (à réfléchir où)
- invalider les PFMPs des élèves sans DA ou sans RIB en prod

**Comment by freesteph** [comment]
pourquoi sans RIB ?

**Comment by JeSuisUnCaillou** [comment]
Valider une pfmp = envoyer en paiement. On peut pas payer sans RIB.

**Comment by AlainSN2** [comment]
cf. #473
