### ISSUE TITLE
Echec de téléchargement des DA

### ISSUE THREAD

**Issue by DiffusionAplyPro** [betagouv/aplypro#344]
Bonjour,

Deux établissements rencontrent des difficultés pour télécharger les zips des DA.

L'établissement : 0510007F - LPO LYC METIER ETIENNE OEHMICHEN CHALONS-EN-CHAMPAGNE
![image](https://github.com/betagouv/aplypro/assets/150439570/f16c537a-d104-4207-a787-b6762832f9f3)
![image](https://github.com/betagouv/aplypro/assets/150439570/bc2b0a84-780a-4032-9e42-035b228a1240)

Le 0590044C - LYCEE POLYVALENT JOSEPH MARIE JACQUARD nous signale:
Lors du téléchargement du fichier des décisions d'attribution, le téléchargement s'arrête arrivé à la taille de 12,39 Mo.
![image](https://github.com/betagouv/aplypro/assets/150439570/93bd0c57-cf21-4b5d-8054-edbd056a8951)
![image](https://github.com/betagouv/aplypro/assets/150439570/57a48d82-da7a-4602-b278-44d8091f8979)

Mickael

Pour suivi : https://sesam.in.orion.education.fr/sesam/view.php?id=462110

**Comment by freesteph** [comment]
https://sentry.incubateur.net/organizations/betagouv/issues/76446/events/74a3db66c6534aaab809ba8473bfa536/?project=109

**Comment by JeSuisUnCaillou** [comment]
Note : ça plante quand des attachments existent sans urls
