### ISSUE TITLE
Ajouter les UAI type `EME` dans la liste 

### ISSUE THREAD

**Issue by freesteph** [betagouv/aplypro#394]
L'établissement IMEPEH d'Arnouville-les-Gonesse (UAI : 0950984D) n'arrive pas à se connecter à cause d'un UAI type `EME`.

```csv
TYPE_UAI,LIBELLE_COURT,LIBELLE_LONG,DATE_OUVERTURE,DATE_FERMETURE,DATE_INTERVENTION,N_COMMENTAIRE,LIBELLE_EDITION
EME,MEDICOEDUC,ETABLISSEMENT MEDICO-EDUCATIF,,,04/12/2013,,Etablissements médico-éducatifs
```

**Comment by JeSuisUnCaillou** [comment]
Note : prévenir de la modif dans le thread email "[MASA] - APLYPRO - nature d'UAI non prise en compte"
