### ISSUE TITLE
Exclure les classes hors contrat des établissements privés sous contrat partiel

### ISSUE THREAD

**Issue by JeSuisUnCaillou** [betagouv/aplypro#397]
On a une liste UAI/MEF des hors contrats, que l'on peut "blacklister" dans l'affichage des élèves
```[tasklist]
### Tasks
- [ ] Supprimer les PFMPs des élèves hors contrat
- [ ] Cacher les élèves hors contrat identifiés par le fichier joint plus bas
```

**Comment by JeSuisUnCaillou** [comment]
Voir l'email "Etablissements privés sous contrat partiel" pour la liste

**Comment by AlainSN2** [comment]
Attention : ne pas se baser sur le MEF qui ne permet pas de distinguer le hors contrat.
SYGNE ne le permet pas non plus : voir possibilité pour la rajouter dans SYGNE. A voir avec Xavier.

**Comment by JeSuisUnCaillou** [comment]
Voici le fichier en question :

[Etablissements privés sous contrat partiel_Liste des UAI et des MEF.xlsx](https://github.com/betagouv/aplypro/files/14561787/Etablissements.prives.sous.contrat.partiel_Liste.des.UAI.et.des.MEF.xlsx)

**Comment by JeSuisUnCaillou** [comment]
Plus de détails sur la tâche :
1. Supprimer ces classes hors contrat (et donc les schoolings et pfmps associées)
2. Ignorer ces classes hors contrat dans le mapper ici, au même titre que celles qui ne sont juste pas dans notre liste de mefs autorisés. https://github.com/betagouv/aplypro/blob/main/app/models/student/mappers/base.rb/#L55-L72
