### ISSUE TITLE
Vérifier que le rib est celui de l'élève si il est majeur

### ISSUE THREAD

**Issue by JeSuisUnCaillou** [betagouv/aplypro#398]
Si la case "compte de représentant légal" est cochée alors que l'élève est majeur, afficher des alertes. 
Les alertes doivent être ignorables. Il peut aussi avoir un mandat pour autoriser de percevoir sur le compte d'un tiers.

**Comment by JeSuisUnCaillou** [comment]
On voudrait voir les élèves devenus majeurs et qui ont des comptes de tiers, et ne pas les envoyer en paiement.

**Comment by DiffusionAplyPro** [comment]
```SQL
select count(distinct el.id) NB_MAJEUR,count(distinct p.id) NB_PAIEMENT
from public.students el
join public.RIBS r on r.STUDENT_ID = el.id and r.PERSONAL=false
left join public.SCHOOLINGS sco on sco.STUDENT_ID = el.id
left join public.PFMPS pfmp on pfmp.SCHOOLING_ID = sco.id
left join public.PAYMENTS p on p.PFMP_ID = pfmp.id
where el.BIRTHDATE+ interval '18 years' > CURRENT_DATE;
```
Actuellement, 209 366 majeurs sur un compte de tiers dont 74 852 paiements validés.
