### ISSUE TITLE
Mise en évidence ou liste des élèves sans SA

### ISSUE THREAD

**Issue by DiffusionAplyPro** [betagouv/aplypro#415]
Bonjour, 

Nous avons la demande suivante : 

Il faudrait qu'il y ait quelque chose qui puisse ramener ou mettre en évidence la liste des élèves pour lesquels il manque la DA: cela simplifierait la vie des établissements.

Mickael

https://sesam.in.orion.education.fr/sesam/view.php?id=468816

**Comment by JeSuisUnCaillou** [comment]
Dévellopement en cours, sera adressé par https://github.com/betagouv/aplypro/issues/284.
![image](https://github.com/betagouv/aplypro/assets/6117264/fdc32c36-43d4-45ba-b091-86d9b6165a43)
