### ISSUE TITLE
Deconnexion utilisateur

### ISSUE THREAD

**Issue by DiffusionAplyPro** [betagouv/aplypro#416]
Bonjour,

Nous avons la demande suivante : 

Est-il possible de faire évoluer le lien déconnexion de APLYPRO?

En effet lorsqu'on clique sur celui-ci, il ramène l'utilisateur sur la mire APLYPRO mais pas sur le portail ARENA. Je propose que ce retour se base sur la fiche LDAP de l'utilisateur pour le ramener vers le bon portail académique ARENA.

Merci de bien vouloir prendre en compte cette demande lors d'une prochaine évolution application.

Mickael

https://sesam.in.orion.education.fr/sesam/view.php?id=468818

**Comment by JeSuisUnCaillou** [comment]
Le site est un url accessible sur internet sans passer forcément par Arena, donc ça serait étrange pour quelqu'un qui a juste été sur aplypro.bta.gouv.fr de se retrouver sur arena une fois déconnecté.
