### ISSUE TITLE
Saisie des RIBS avec les espacement pour faciliter la lecture

### ISSUE THREAD

**Issue by DiffusionAplyPro** [betagouv/aplypro#420]
Bonjour,

Nous avons la demande d'évolution suivante : 

Serait-il possible d'envisager l'évolution suivante en l'occurrence avoir des sauts tous les 4 caractères dans la saisie des RIBS pour faciliter la relecture comme sur Siècle ?

Mickael

https://sesam.in.orion.education.fr/sesam/view.php?id=468975

**Comment by JeSuisUnCaillou** [comment]
Duplicate of https://github.com/betagouv/aplypro/issues/254
