### ISSUE TITLE
1 PDF de DA par classe pour ne pas avoir à lancer X impressions

### ISSUE THREAD

**Issue by DiffusionAplyPro** [betagouv/aplypro#424]
Bonjour,

L'établissement me fait remarquer que pour la distribution, il faut qu'ils ouvrent tous les pdf et les impriment un par un, ce qui est énergivore (686 pdf à éditer !!!)
Il faudrait que l'option édition propose aussi d'éditer tous les pdf ensembles, avec un tri par classe, afin de pouvoir ensuite les distribuer.

Mickael

@JeSuisUnCaillou Test de notif

https://sesam.in.orion.education.fr/sesam/view.php?id=469281

**Comment by JeSuisUnCaillou** [comment]
Là à mon avis y'a un moyen de trouver une solution en dehors d'APLyPro. Il doit être possible d'imprimer tous les fichiers d'un dossier, à voir avec leurs admins systèmes car ca dépend des configurations de leurs OS.

Le mieux étant encore de les déposer sur un repo de documents dématéralisé accessible par les étudiants, les établissements sont censés avoir des outils pour ça.
