### ISSUE TITLE
Contrainte d'unicité par pfmp sur les paiements requests "en cours" (non échouées)

### ISSUE THREAD

**Issue by JeSuisUnCaillou** [betagouv/aplypro#434]
Lorsqu'un directeur a un réseau lent et qu'il clique plusieurs fois sur le bouton "valider les PFMPs" par impatience, ça peut générer plusieurs paiements par PFMPs.

**Comment by DiffusionAplyPro** [comment]
Je ne sais pas si c'est en rapport ou non.
```SQL 
select P.PFMP_ID,id,P.AMOUNT,P.CREATED_AT,P.UPDATED_AT 
from public.PAYMENTS p 
join  (
        select p.PFMP_ID 
        from public.PAYMENTS p 
        GROUP BY PFMP_ID 
        HAVING count(distinct id)>1
       ) DOUBLON ON DOUBLON.PFMP_ID = P.PFMP_ID
;
```

On se retrouve avec des PFMP créées à des dates différentes donc pas en rapport avec une lenteur lors de la 1ere validation.

pfmp_id | id | amount | created_at | updated_at
-- | -- | -- | -- | --
899 | 1 | 400, | 14/11/2023 10:47:49 | 14/11/2023 10:47:49
899 | 1873 | 400, | 29/11/2023 10:35:04 | 29/11/2023 10:35:04

**Comment by JeSuisUnCaillou** [comment]
Sera nettoyé par https://github.com/betagouv/aplypro/issues/336

**Comment by JeSuisUnCaillou** [comment]
Ca devient aujourd'hui : "Il ne faut pas qu'il y ait plus d'une payment request non échouée à la fois"
Echoué = status de `:rejected`, `:unpaid`.

**Comment by JeSuisUnCaillou** [comment]
```ruby
Pfmp.joins(:payment_requests).having("count(asp_payment_requests.id) > 1").group(:id).
count
=> {962923=>2}
Pfmp.find(962923).payment_requests.map(&:current_state)
=> ["paid", "rejected"]
```

Manifestement, on n'a plus de doublons en prod.
