### ISSUE TITLE
Recette de paiments avec l'ASP

### ISSUE THREAD

**Issue by JeSuisUnCaillou** [betagouv/aplypro#436]
En attente d'un retour de Gaëtan sur le paiement envoyé (on a déjà eu un retour quant à l'individu)

**Comment by JeSuisUnCaillou** [comment]
Gaëtan nous a confirmé que le paiement a été liquidé dans SERAPIS, en recette.
Il est bien revenu payé en retour. -> Fichier "renvoi_paiement_EXEMPLE_GRATIF_20230109100600.xml"

**Comment by freesteph** [comment]
OK je m'attendais à une notif via notre email ASP (qui est notifié pour les intégrations d'individu), au temps pour moi. J'ai bien vu le fichier.
