### ISSUE TITLE
Implémenter le mapping SYGNE -> INSEE

### ISSUE THREAD

**Issue by freesteph** [betagouv/aplypro#443]
Les codes pays SYGNE ont leur propre référentiel indiqué par le fichier attaché. L'ASP a besoin du "vrai" code pays INSEE.

[liste_pays.xlsx](https://github.com/betagouv/aplypro/files/14179343/liste_pays.xlsx)

**Comment by freesteph** [comment]
```ruby
Student.distinct.pluck("address_country_code").uniq
```

**Comment by JeSuisUnCaillou** [comment]
Code pays de l'adresse d'un élève sygne : 99100 OK
Code pays de l'adresse d'un élève sygne : 100 PAS OK
-> rajouter le 99 devant avant de passer le code à l'ASP
