### ISSUE TITLE
Nettoyer les élèves de l'année précédente d'un établissement

### ISSUE THREAD

**Issue by DiffusionAplyPro** [betagouv/aplypro#451]
Un établissement de Wallis et Futuna s'est connecté à APLyPro dès novembre 2023, alors que cette académie était encore sur l'année scolaire 2022.

A ce jour, l'établissement, vient de faire sa rentrée 2023 et lors d'une nouvelle connexion APLyPro, l'établissement se retrouve avec les élèves déscolarisés de l'année scolaire précédente et ceux de cette année scolaire.

Il n'y a donc pas de gestion d'années scolaire dans APLyPro ce qui est assez problématique pour la continuité du projet.

Pour cet établissement, il faudrait donc supprimer toutes les données élèves classe et schooling en base afin de lui permettre de repartir de 0 pour que les données soient propres. Seule une PFMP globale sur une classe a été saisie. J'ai demandé que plus rien ne soit fait en attendant que la RAZ soit faite.

Etab id : 1747

Mickael

https://sesam.in.orion.education.fr/sesam/view.php?id=474527

**Comment by JeSuisUnCaillou** [comment]
Pas besoin de traiter ce problème, cette académie n'est pas concernée par la mesure.
