### ISSUE TITLE
Empêcher l'accès à certaines académies non concernées par l'allocation (Nouvelle-Calédonie, Polynésie française et Wallis-et-Futuna)

### ISSUE THREAD

**Issue by AlainSN2** [betagouv/aplypro#469]
**Nouvelle-Calédonie**, **Polynésie française** et **Wallis-et-Futuna** ne sont pas concernés par les dispositions de l’allocation.
Le nécessaire va être fait par le pôle identité au niveau de la politique d'habilitation pour que l'application ne remonte plus dans l'ARENA mais un blocage supplémentaire est à prévoir au niveau d'APLyPro.

**Comment by DiffusionAplyPro** [comment]
```SQL
select *
from public.ESTABLISHMENTS et
where et.ACADEMY_CODE in ('40','41','42')
```

Deux établissements concernés actuellement.
Polynesie = academie_code = 41

**Comment by AlainSN2** [comment]
Bloquer les mises en paiements des ces académies

**Comment by DiffusionAplyPro** [comment]
il faut bloquer l'acces aplypro et supprimer les données qui sont redescendues

**Comment by JeSuisUnCaillou** [comment]
Supprimer les établissements de Wallis & Futuna, Nouvelle Calédonie (et Polynésie française) de la BDD

**Comment by pskl** [comment]
Create exclusions for for uai: `9870026P` and `9830006P`

**Comment by pskl** [comment]
Still do: not list excluded establishments from stats
