### ISSUE TITLE
Gestion du changement d'année

### ISSUE THREAD

**Issue by AlainSN2** [betagouv/aplypro#497]

**Comment by AlainSN2** [comment]
Permettre au chef d'établissement de consulter l'historique par année scolaire : à préciser. Quelles historiques : par année, classe, élève, PFMP, montant total ou par PFMP, statut paiement, les DA et les états liquidatifs ?  

Solution SI à mettre en œuvre : rajouter une table avec une premier ligne pour l'année courante, rattacher toutes les scolarités actuelles à cette année là, et faire en sorte que chaque été une nouvelle année soit créée dans la table et que les nouvelles scolarités récupérées y soient automatiquement rattachées.

Cette demande est à traiter dans un second temps après les paiements.

**Comment by JeSuisUnCaillou** [comment]
# Techniquement
Il faut qu'on prépare une table `school_year` et un modèle `SchoolYear`, avec une relation `belongs_to` entre `Classe` et `SchoolYear`.
Y'a aussi une relation entre `Mef` et `SchoolYear` peut-être, pour le versionning des mefs. Et je pense que c'est tout, les pfmps étant reliées aux schoolings, qui sont reliées au classes, on aurait tout scopé.

Et faudrait scoper quasi toutes les routes dans`school_year/:id/...`
Et ajouter un sélecteur de schoolyear dans la home.

Et on aurait une méthode `SchoolYear#current` pour choper la current par défaut.

**Comment by JeSuisUnCaillou** [comment]
Idée pour gérer de manière souple la création de nouvelles classes rattachées à une nouvelle année scolaire :

Dans ce fichier : https://github.com/betagouv/aplypro/blob/stats_of_payments/app/models/student/mappers/sygne.rb
On y parse le résultat de la liste des élèves d'un établissement (exemple de mock [ici](https://github.com/betagouv/aplypro-mock-data/blob/data/sygne-students-for-uai.json) ). L'idée c'est de faire une requête supplémentaire par étudiant pour récupérer la date de début de sa scolarité pour savoir à quelle année scolaire doit être rattachée la classe.

**Comment by gtournadre** [comment]
[Analyse_Changement_Annee_Scolaire.pdf](https://github.com/user-attachments/files/15530970/Analyse_Changement_Annee_Scolaire.pdf)
