### ISSUE TITLE
Invalider les dates hors calendrier et prévenir les établissements de leurs erreurs de saisies

### ISSUE THREAD

**Issue by JeSuisUnCaillou** [betagouv/aplypro#556]
Invalider les PFMPs avec des dates en dehors de l'année scolaire dans la base de données de production

Prévenir l'établissement : Notification dans l'application ?

**Comment by JeSuisUnCaillou** [comment]
Nettoyage lié à https://github.com/betagouv/aplypro/issues/285

**Comment by gtournadre** [comment]
Terminé par #557
