### ISSUE TITLE
remplacer les adresses d'élèves résidant à l'étranger par une adresse fixe

### ISSUE THREAD

**Issue by JeSuisUnCaillou** [betagouv/aplypro#569]
Solution proposée par Gaëtan, pour les élèves résidants à l'étranger : Renplacer leur code de pays et leur code ville par ce lui d'un bâtiment public convenu à l'avance.

Penser à envoyer aussi l'adresse complète dans le flux, pour être sûr de n'avoir aucune ambiguité

**Comment by freesteph** [comment]
Celle de l'établissement ?

**Comment by tnicolas1** [comment]
@pskl Cette tâche est faite ?

**Comment by gtournadre** [comment]
#1056
