### ISSUE TITLE
Contrôles supplémentaires pré-paiement

### ISSUE THREAD

**Issue by JeSuisUnCaillou** [betagouv/aplypro#571]
- ne pas encore envoyer les élèves résidants à l'étranger ~~(besoin de mettre le code commune de l'étab à la place pour que ça soit intégré par serapis)~~
- date de fin de pfmp doit être dans le passé

**Comment by gtournadre** [comment]
Le fonctionnement d'APLyPro au 18/10/2024 comprend ces améliorations
