### ISSUE TITLE
Les RIBs doivent être de la zone SEPA (checker les codes pays des IBAN)

### ISSUE THREAD

**Issue by JeSuisUnCaillou** [betagouv/aplypro#619]

**Comment by DiffusionAplyPro** [comment]
https://www.telepaiement.dgfip.finances.gouv.fr/stl/satelit.web?templatename=accueilinfoedito&codeedito=PL10&retourliste=PL

               Allemagne,DE
                Autriche,AT
                Andorre,AD
                Belgique,BE
                Bulgarie,BG
                Cité du Vatican,VA
                Chypre,CY
                Croatie,HR
                Danemark,DK
                Espagne,ES
                Estonie,EE
                Finlande,FI
                France,FR
                Gibraltar,GI
                Grèce,GR
                Hongrie,HU
                Irlande,IE
                Islande,IS
                Italie,IT
                Lettonie,LV
                Liechtenstein,LI
                Lituanie,LT
                Luxembourg,LU
                Malte,MT
                Monaco,MC
                Norvège,NO
                Pays-Bas,NL
                Pologne,PL
                Portugal,PT
                République Tchèque,CZ
                Roumanie,RO
                Royaume-Uni,GB
                Saint-Marin,SM
                Slovaquie,SK
                Slovénie,SI
                Suède,SE
                Suisse,CH

J'ai rajouté les codes pays

Dans les PFMP validées tous les RIB sont en zone SEPA.
