### ISSUE TITLE
Permettre la modification d'une PFMP validée si aucune requête de paiement n'est en cours

### ISSUE THREAD

**Issue by freesteph** [betagouv/aplypro#633]
La logique actuelle : 

```ruby
  def can_be_modified?
    if in_state?(:validated)
      payment_requests.all?(&:stopped?)
    else
      true
    end
  end
```

n'inclue pas les requêtes `pending` qui ne devraient pas empêcher non plus la modification.

**Comment by JeSuisUnCaillou** [comment]
Je pourrais répondre à deux établissements qui me demandaient de modifier/supprimer des PFMPs validées, quand ça sera déployé
