### ISSUE TITLE
Les utilisateurs ne comprennent pas qu'on a séparé les classes en plusieurs quand elles ont plusieur formations

### ISSUE THREAD

**Issue by JeSuisUnCaillou** [betagouv/aplypro#652]
```[tasklist]
### Tasks
- [x] Renommer la page "Liste des classes et formations"
- [x] Afficher un titre pour chaque classe, et sous le titre la liste des formations de la classe
```

**Comment by freesteph** [comment]
On pourrait peut-être distinguer la formation un peu mieux dans la ligne de la classe (qui est pour le moment une bête méthode qui fait `[classe.label, mef.specialty].join(" - ")`

Genre avec un badge : 
![Capture d’écran 2024-04-03 à 11 46 08](https://github.com/betagouv/aplypro/assets/107635/ef2c4641-8ae3-4f2e-90c5-cf9d72c5f0a3)

**Comment by freesteph** [comment]
et même qu'on pourrait rajouter un filtre en cliquant sur le badge du coup

**Comment by JeSuisUnCaillou** [comment]
Ah zut, j'avais pas vu tes suggestions.

Mais du coup ça a été fait ici : https://github.com/betagouv/aplypro/pull/740
