### ISSUE TITLE
Stocker toutes les données sur `ASP::PaymentRequest`

### ISSUE THREAD

**Issue by freesteph** [betagouv/aplypro#658]
Historiquement la validation des PFMPs été décorrélée de la présence des infos nécessaires à l'envoi en paiement pour fluidifier le processus. La raison était simple : un élève qui a fait X jours de stages a le droit de toucher N euros (i.e voit sa PFMP validée) même sans qu'il ait fourni ses coordonnées bancaires.

Désormais il semble plus judicieux de réduire ces deux étapes en une, celle d'"envoi en paiement" qui implique la validation du montant décerné à l'élève, *sous réserve* que toutes les données et conditions nécessaires au paiement sont bien réunies.

Bénéfices majeurs : 
- stockage donc historique de la donnée attachée à une requête de paiement (au lieu d'un lien dynamique vers des données changeantes) c.f #562 ;
- validations statiques (i.e `validates_presence_of :attributive_decision_number` au lieu de `validates -> { request.pfmp.schooling.attributive_decision.attached?`) ;
- simplification de la création du XML ASP puisque la requête encapsulera toute la donnée nécessaire (décalage du mapping en amont)
- état liquidatifs "stabilisés" dans la requête.

**Comment by gtournadre** [comment]
Le fonctionnement d'APLyPro au 8/10/2024 contient cette amélioration
