### ISSUE TITLE
Empêcher la maj de rib associé à une pfmp "locked"

### ISSUE THREAD

**Issue by JeSuisUnCaillou** [betagouv/aplypro#704]

**Comment by pskl** [comment]
Pour réussir à implémenter ça il va falloir que tu ajoutes ce que l'on appelle une validation.

[Tu peux lire un peu plus ici](https://guides.rubyonrails.org/active_record_validations.html)

Une validation qui peux t'inspirer c'est "single_active_payment_request_per_pfmp" sur le modèle Pfmp.

Tu pourrais écrire une validation sur le modèle RIB par exemple qui check la PFMP associée.
