### ISSUE TITLE
[extract] données manquantes

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/aplypro#73]
https://mattermost.incubateur.net/betagouv/pl/3ecfe346pprj5jn47omieuhc1o

**Comment by JeSuisUnCaillou** [comment]
Tu nous donne un peu de contexte ? :)

**Comment by mxmeunier** [comment]
> Tu nous donne un peu de contexte ? :)
> Quel est le rapport avec aplypro ?

Mauvaise attribution et je n'ai pas pu modifier donc j'ai supprimé le ticket. :(
