### ISSUE TITLE
DEBUG de l'envoi de fichiers dupliqués du 15 avril

### ISSUE THREAD

**Issue by JeSuisUnCaillou** [betagouv/aplypro#732]
On a plusieurs problèmes avec le retour SERAPIS d'aujourd'hui: 

## 17 fichiers de retour pour 7 fichiers envoyés hier.
On dirait que les fichiers de retour ont été split, car nous retrouvons certaines PaymentRequest dans les fichiers de retour qui ne correspondent à aucun fichier d'envoi.

Ca nous casse un peu le sytème de récupération de fichiers. Il faudrait le changer pour faire le lien avec le parsing des lignes, plutôt qu'avec le nom du fichier (comme pour les retours de paiement)

**EDIT** : en fait on avait un job en retry qui envoyait le même fichier en boucle et buguait au moment de passer les paymentRequest en :sent.
Les 10 fichier suivants portent les mêmes enregistrements : 

["nps_ficimport_idp_aplypro_production_20240415160251.xml",
 "nps_ficimport_idp_aplypro_production_20240415160655.xml",
 "nps_ficimport_idp_aplypro_production_20240415161105.xml",
 "nps_ficimport_idp_aplypro_production_20240415161532.xml",
 "nps_ficimport_idp_aplypro_production_20240415162133.xml",
 "nps_ficimport_idp_aplypro_production_20240415163046.xml",
 "nps_ficimport_idp_aplypro_production_20240415164559.xml",
 "nps_ficimport_idp_aplypro_production_20240415171134.xml",
 "nps_ficimport_idp_aplypro_production_20240415175601.xml",
 "nps_ficimport_idp_aplypro_production_20240415190930.xml"]

## Erreurs "Le numéro administratif <blabla> n'est pas unique"
Cette erreur décrit un numéro de DA n'étant "pas unique". 
**EUREKA** : Avant on avait un filtre qui ne sélectionnait que les "premières schoolings" d'étudiants, pour éviter d'envoyer des DA qui nécessitent une abrogation de la DA précédente

**EDIT** : A priori; ces rejets sont dûs aux duplications de fichiers ci dessus.

## Certains numéros de DA sont incomplets
Leur schooling n'a pas de`administrative_number`

**Comment by freesteph** [comment]
C'est un retry de Sidekiq

**Comment by JeSuisUnCaillou** [comment]
Ce qu'on a appris : 

- Ne pas retry les jobs d'envois de fichiers à l'ASP : https://github.com/betagouv/aplypro/pull/735
- Vérifier le state des payment_requests traitées par le job d'envoi de fichiers : TODO
- Checker la longueur du numéro administratif, car des fois les Schoolings n'ont pas de numéro adm malgré le fait qu'elles ont une DA ([la migration](https://github.com/betagouv/aplypro/blob/main/db/migrate/20240219100348_add_administrative_number_to_schoolings.rb) aurait échoué ?)

**Comment by JeSuisUnCaillou** [comment]
https://github.com/betagouv/aplypro/issues/754
