### ISSUE TITLE
Rendre PollPaymentsServerJob transactionnel

### ISSUE THREAD

**Issue by pskl** [betagouv/aplypro#746]
⚠ ⚠⚠

Car il appelle PaymentsFileReader par exemple qui fait des updates et des changements d'états

A l'heure actuelle nous sommes exposés à des problèmes en cas d'erreur en cours de lecture de fichiers ou autres (extrêmement délicat à corriger en cas de conflit je suppose).

**Comment by freesteph** [comment]
Closed by #812
