### ISSUE TITLE
Gérer la validité des Codes BIC (les BIC du crédit mutuel se terminant par "ARK" doivent être envoyés à l'ASP en se terminant par XXX)

### ISSUE THREAD

**Issue by JeSuisUnCaillou** [betagouv/aplypro#795]
Note: Penser à renvoyer en paiement les PaymentRequest échouées qui ont un RIB dont le BIC se termine par "ARK", une fois ce fix effectué.

**Comment by gtournadre** [comment]
Il y a d'autre cas de BIC qui sont saisis correctement mais qui ne sont pas dans le référentiel ASP. Esgt-ce qu'on peut envisager une sorte de tableau de correspondance : BIC Saisie --> BIC corrigé à mettre dynamiquement dans le fichier de l'ASP?

**Comment by JeSuisUnCaillou** [comment]
Pour info : La "traduction" de BIC pour l'ASP se fait déjà ici : https://github.com/betagouv/aplypro/blob/main/app/services/asp/mappers/coord_paie_mapper.rb/#L67-L77

On a aujourd'hui un mécanisme qui ajoute "XXX" à la fin d'un BIC quand celui-ci est trop court.

Tu peux t'insérer dans cette méthode pour rajouter le cas des BIC Crédit Mutuel Arkea dont le BIC se termine par "ARK" et dont il faudrait enlever les derniers caractères.

**Comment by gtournadre** [comment]
Les test unitaires à compléter
https://github.com/betagouv/aplypro/blob/main/spec/services/asp/mappers/coord_paie_mapper_spec.rb

**Comment by gtournadre** [comment]
Idéalement, il faudrait créer un référentiel des codes BIC dans la base de données, avec au moins 3 colonnes : le code BIC officiel, le nom de la banque et la valeur qu'on doit envoyer dans le fichier ASP. On se servira de cette table pour transformer à la volée les codes BIC qu'on envoie dans le fichier ASP afin de sécuriser au maximum les paiements. 
 @ac-clermont-dylan  je te fait passer la liste des codes BIC liés à des paiements qui ont d'ores et déjà fonctionné.

**Comment by pskl** [comment]
Je vote pour l'amélioration du `CoordPaieMapper` plutót que l'approche de stockage de données supplémentaires. cc @JeSuisUnCaillou
