### ISSUE TITLE
Mettre à jour la FàQ dans APLyPro

### ISSUE THREAD

**Issue by gtournadre** [betagouv/aplypro#854]
Mettre à jour la FàQ avec le lien vers celle de la DGSCO : https://eduscol.education.fr/document/53313/download

La FàQ dans APLyPro est ici : 
https://github.com/betagouv/aplypro/blob/stats_of_payments/config/locales/faq.yml

**Comment by gtournadre** [comment]
J'ai aussi attaqué à rédiger un "quoi de neuf" APLyPro, il faudra l'intéger sous la forme HTML ou en lien vers un PDF

**Comment by gtournadre** [comment]
Remplacer le contenu du premier paragraphe par : Les paiements des PFMP ont débuté en avril 2024, et le rattrapage des PFMP effectuée en entre la rentrée et la fin de l'année 2023 est en cours. 
Les mise en paiement interviennent dorénavant au fil de l'eau et des développement sont en cours pour vous permettre de corriger et de renvoyer en paiement les demandes de paiement bloquées.

**Comment by tnicolas1** [comment]
Merge #888
