### ISSUE TITLE
Les paiement échoués (unpaid) ne devraient pas pouvoir être relancés

### ISSUE THREAD

**Issue by pskl** [betagouv/aplypro#858]
Limiter l'affichage du bouton

**Comment by gtournadre** [comment]
En attendant l'atelier d'avoir plus d'informations de la part de l'ASP

**Comment by pskl** [comment]
NOTE: discussion du mardi 7 mai avec @gtournadre et @JeSuisUnCaillou soulevait la question sur ce sujet: est-ce une contrainte légitime ou un manque de clarification sur les raisons de non-paiement? 

La perspective coté developpeur étant que le bouton devrait rester actionnable pour les unpaid.

**Comment by gtournadre** [comment]
A bloquer pour l'utilisateur le temps de trouver une procédure avec l'ASP
