### ISSUE TITLE
Intégrer en base les raisons d'incomplétion des demandes de paiement.

### ISSUE THREAD

**Issue by gtournadre** [betagouv/aplypro#863]
Il faut jouer le job de passage à "Ready" des payment requests afin d'avoir en base les causes d'incomplétion d'une demande de paiement.

**Comment by pskl** [comment]
Mon plan: avant de déployer, pour s'assurer que toutes les raisons sont stockées:

```ruby
ASP::PaymentRequest.in_state(:incomplete).find_each(batch_size: 10000) do |pr|
  pr.mark_ready!
end
```
