### ISSUE TITLE
Lancer un appel unitaire en masse à Fregata pour raptrier Schoolings.Status quand il est à null

### ISSUE THREAD

**Issue by gtournadre** [betagouv/aplypro#893]
Une demande de paiement de paiement est bloquée quand le statut de la schooling n'est pas 0 (Scolaire). Or au 16 mai 2024, 101415 schoolings n'ont pas le statut scolaire, dont 69191 valeurs nulles ou autres. Il convient de lancer un appel à Sygne (unitaire par ine de l'élève) pour mettre à jour le status sur ces schoolings qui ont status is null. Une élvolution de Sygne est prévue pour permettre d'avoir le statut scolaire directement dans la liste des élèves par établissement, ce qui permettra de ne pas importer les apprentis dans APLyPro.

**Comment by gtournadre** [comment]
Fermé par l'issue #908

**Comment by gtournadre** [comment]
Traité par le biais de l'issue #908 . Merci @freesteph

**Comment by freesteph** [comment]
Pour des raisons pour l'instant inconnues, certains établissements du MASA ont un `students_provider: "sygne"`, ce qui les empêche de récupérer les bonnes infos (ils n'en ont aucune puisque SYGNE ne renvoie rien pour eux).

 Pour restaurer la bonne source et permettre la bonne mise à jour – notamment – des status :

```ruby
bin/rails c # en production/scalingo

establishment = Establishment.find_by(uai: <UAI>)
establishment.update!(students_provider: "fregata")

FetchStudentsJob.perform_later(establishment)
```

**Comment by pskl** [comment]
Traité durant l'été 2024
