### ISSUE TITLE
Débloquer les envois de paiement à cause d'un numéro administratif trop long

### ISSUE THREAD

**Issue by freesteph** [betagouv/aplypro#930]
Rapporté par Sentry ce matin : https://sentry.incubateur.net/organizations/betagouv/issues/102402/?project=109&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=24h

> ActiveModel::ValidationError SendPaymentRequestsJob
> Validation échouée : Numadm est trop long (pas plus de 19 caractères) (ActiveModel::ValidationError)

Ce qui a bloqué tous les envois subséquents. Il faut trouver le dossier en cause (c'est sûrement une histoire de numéro de décision attributive trop long, c.f #792 ).

https://github.com/betagouv/aplypro/blob/0eee4c04dcfca5b792284d2041815bed1d3d1ea4/lib/asp/entities/dossier.rb#L17

**Comment by freesteph** [comment]
Après une enquête en production pour trouver toutes les requêtes prêtes dont la génération de XML est invalide : 

```ruby
ASP::PaymentRequest
  .in_state(:ready)
  .find_each do |req|
  begin
    ASP::Entities::Fichier.new([req]).valid?
  rescue
    puts "Failed to construct with: #{req.id}"
  end
end
```

On obtient ces IDs de requête : 

```ruby
["656602", "656657", "656763", "656847", "656866", "656901", "657026", "657040", "657045", "657069", "657145", "657298", "657341"]
```

Si on regarde le numéro administratif du dossier (i.e schooling) d'une requête : 

```ruby
irb(main):138> ASP::PaymentRequest.find(656602).schooling.attributive_decision_number
ASP::PaymentRequest.find(656602).schooling.attributive_decision_number
=> "MENJ_OTHERZYBIFQ7HR420231"
```

C'est bien ce `OTHER` de `MENJ_OTHER` qui fait planter la requête, et qui se retrouve dans le `bop_indicator` à cause de : 

https://github.com/betagouv/aplypro/blob/0eee4c04dcfca5b792284d2041815bed1d3d1ea4/app/models/establishment.rb#L101-L110

Le `:other` est retourné si on ne connait pas le code de l'établissement. 

Les requêtes pointent vers le même établissement : 

```ruby
irb(main):134> ASP::PaymentRequest.where(id: problems).map { |request| request.pfmp.establishment }.uniq
ASP::PaymentRequest.where(id: problems).map { |request| request.pfmp.establishment }.uniq
=> 
[#<Establishment:0x00007fad45423480
  id: 3568,
  uai: "0400802E",
  name: "Maison Familiale Rurale de Pontonx-sur-l'Adour",
  denomination: "MAISON FAMILIALE RURALE EDUCATION ORIENT",
  nature: nil,
  created_at: Fri, 01 Dec 2023 08:14:18.918318000 UTC +00:00,
  updated_at: Mon, 27 May 2024 13:21:06.577169000 UTC +00:00,
  postal_code: "40465",
  city: "Pontonx-sur-l'Adour",
  telephone: "0558572042",
  email: "mfr.pontonx@mfr.asso.fr",
  fetching_students: false,
  address_line1: "206 avenue du marensin",
  address_line2: nil,
  private_contract_type_code: "60",
  academy_code: "04",
  academy_label: "Bordeaux",
  students_provider: "fregata",
  ministry: "AGRICULTURE",
  confirmed_director_id: 6528,
  department_code: "040">]
  ```

Dont le `private_contract_type_code` (60) n'est pas dans ceux qu'on stocke : 

```ruby
https://github.com/betagouv/aplypro/blob/0eee4c04dcfca5b792284d2041815bed1d3d1ea4/app/models/establishment.rb#L55-L59
```

Si on suit le commentaire du code qui indique [les correspondances dans la table de la BCN](https://infocentre.pleiade.education.fr/bcn/workspace/viewTable/n/N_CONTRAT_ETABLISSEMENT) on constate un nouveau code `60` rajouté... le 25/04/2024.

Il faut que l'on rajoute ce code dans les privés pour bien avoir `menj_private` en retour. C'est un établissement MASA sous contrat privé qui fournit un diplôme MENJ.

**Comment by gtournadre** [comment]
Merci, belle investigation

**Comment by gtournadre** [comment]
J'ai cet établissement dans Sygne mais sans scolarités associées.
