### ISSUE TITLE
Investigate 403 sur la checkbox de confirmed director pour la validation des PFMPS

### ISSUE THREAD

**Issue by pskl** [betagouv/aplypro#955]

**Comment by JeSuisUnCaillou** [comment]
ça se passe ici : https://github.com/betagouv/aplypro/blob/main/app/views/pfmps/show.html.haml/#L47-L48

Il faudrait rajouter une condition sur le role de directeur pour que seuls eux voient ces partiales.

Et au passage, on pourrait aussi mettre un message pour les non directeurs, leur indiquant que seul un directeur peut relancer le paiement.
