### ISSUE TITLE
Récupération du statut élève sur leur scolarité fermée.

### ISSUE THREAD

**Issue by DiffusionAplyPro** [betagouv/aplypro#977]
Bonjour,

Il semblerai qu'il y ait un souci pour récupérer le statut des élèves lorsque ceux-ci ont plus d'une scolarité.

id student 292278	-> id scolarité 293974
id student 291180	->  id scolarité293165

Pas de status dans la sco. 
L'intérogation du endpoint élève sygne/api/v1/eleves/INE ne renvoie que la scolarité actuelle de l'élève.

Mickael
https://sesam.in.orion.education.fr/sesam/view.php?id=495633

**Comment by freesteph** [comment]
Vu avec @DiffusionAplyPro les status sont bien redescendus grâce aux jobs lancés par @pskl (je suppose).
