### ISSUE TITLE
Fin de l'exposition des données de Sygne pour 2023-2024 à partir du 15 Août

### ISSUE THREAD

**Issue by gtournadre** [betagouv/aplypro#980]
Dans Sygne la Bascule d'année scolaire se fera le 19 juin. a partir de cette date, on va remonter des données de scolarité de 2024 / 2025. Il faut donc arrêter d'interroger Sygne depuis APLyPro à partir du 19 juin 2024 tant que la gestion d'année scolaire n'est pas opérationnelle.

**Comment by pskl** [comment]
Au final il se trouve que la date de fin d'exposition est le 15 août. Donc je remet dans le backlog.

**Comment by tnicolas1** [comment]
@pskl Cette tâche est faite ?
