### ISSUE TITLE
Autoriser l'Institut Agro Dijon site de Marmilhat

### ISSUE THREAD

**Issue by JeSuisUnCaillou** [betagouv/aplypro#989]
Le directeur de l'établissement UAI:0632001H n'a pas accès à aplypro.

C'est par ce que le "type d'UAI" de son FrEduRneResp a un type qu'on n'autorise pas encore : "CONT" (FORMATION CONTINUE OU INTERNIVEAUX)
voir : https://github.com/betagouv/aplypro/blob/main/app/models/establishment.rb/#L35-L37

Pour l'autoriser à entrer, on peut:
- autoriser tous les établissements de type CONT
- autoriser juste cet utilisateur à avoir des droits de directeur sur l'étab 0632001H

Pour la deuxième option, il faudrait idéalement rebrancher le masa sur keycloak au lieu de les faire rediriger directement sur l'app, pour pouvoir ajouter un AplyproResp=0632001H à ce directeur. En moins compliqué, on peut ajouter une condition dégueu dans le callback controller (ou plutôt dans le IdentityMappers::Cas) pour autoriser son email particulier à entrer.

**Comment by JeSuisUnCaillou** [comment]
Pour rebrancher le masa sur keycloak @freesteph , de souvenir on peut le faire en SAML2, tu saurais nous écrire un peu plus de détails sur comment faire ?

**Comment by freesteph** [comment]
Hélas non. Ils proposent une intégration en SAML2 ou en OAuth, on a choisi le dernier parce qu'on était familiers avec mais pas plus.

Il faudrait demander une intégratio SAML2 aux équipes de FREGATA puis trouver/acquérir les connaissances pour les intégrer dans notre Keycloak. Je pense pas que ce soit si dur que ça mais à l'époque on avait pas les ressources temps pour étudier SAML2.
