### ISSUE TITLE
Recensement + implementation des tâches de support qui peuvent devenir des tâches de développement

### ISSUE THREAD

**Issue by pskl** [betagouv/aplypro#997]
Recensons dans ce ticket tous les cas qui peuvent être "retry" en automatique:

## ex de tâches one-off qui rentrent dans le cadre du support: 
- le cas des apprentis dont il manquait la scolarité -> DONE (here we do a Preparejob on it to retransition from incomplete to incomplete to update the wording, SUPPORT)

```rb
missing_scol = ASP::PaymentRequest.in_state(:incomplete).where(
  "metadata LIKE ?",
  "%\"incomplete_reasons\":{\"ready_state_validation\":[\"L'élève doit avoir un statut scolaire. Causes possibles de blocage : l'élève a un statut d'apprenti, un autre statut, ou le statut n'est pas renseigné.\"]%"
)

res=0

missing_scol.find_each(batch_size: 10000) do |pr|
  begin
    PreparePaymentRequestJob.perform_later(pr)
    puts "."
    res += 1
  rescue Statesman::TransitionFailedError
    puts 'x'
  end
end
```

- rejected pour cause de iban ARK  (also one-off, SUPPORT)
Ici on va recréer une demande de paiement car l'état précédent est rejected donc final (possible de le relancer pour l'utilisateur mais on veut lui faciliter la tâche car techniquement il n'a pas fait d'erreur de saisie

```rb
a = Pfmp.find(xxx) # ou autre query
PfmpManager.new(a).create_new_payment_request!
```

## exemples de demandes qui requièrent potentiellement un développement produit:

- 1) ex: regénérer les DA d'un etab:

Pour soulagement immédiat on peut faire tourner le script suivant:

```rb
uai = "XXXXX"
e = Establishment.find_by!(uai: uai)
# Si on considère que le chagement d'info a bien été fait au préalable
e.schoolings.each do |s|
  GenerateAttributiveDecisionJob.perform_later(s)
end
```

Mais idéalement c'est un bouton qui devrait être accessible à l'utilisateur directement

- 2) Supprimer les schoolings "Fantômes" 

script SQL by @gtournadre 

Devrait être un cleanup régulier automatique

- 3) ex: MAJ d'une scolarité d'un étudiant:

```rb
s=Student.find(xxxx)
FetchStudentSchoolingsInformationJob.perform_now(student)
```

- 4) Ratiboisage des numero de versions d'attribution decision:

```rb
Schooling.where('attributive_decision_version > ?', 9).update_all(attributive_decision_version: 9)
```

- 5) Update des classes
```rb
# Will fetch listings and close students that are not in there anymore

e = Establishment.find_by(uai: "XXXX")

FetchStudentsJob.perform_later(e)
```

**Comment by gtournadre** [comment]
Le cas des rejected pour cause de ARK dans le code BIC de la banque

**Comment by gtournadre** [comment]
Liste des scolarités insconsitantes : 
WITH SCO_INC AS (
        select UAI,student_id,sco_id,end_date,NB_PFMP,NB_SCO NB_SCO_STUDENT
        FROM ( 
                select  sco.STUDENT_ID,sco.id SCO_ID,end_date,et.uai
                       ,COALESCE(pf.NB_PFMP,0) NB_PFMP
                       ,NB_SCO
                       ,RANK() OVER (PARTITION BY sco.STUDENT_ID ORDER BY NB_PFMP DESC) RANG
                from public.SCHOOLINGS sco
                join public.classes c on c.id = sco.CLASSE_ID
                join public.ESTABLISHMENTS et on et.id = c.ESTABLISHMENT_ID
                left join (
                                select pf.SCHOOLING_ID,count(*) NB_PFMP
                                from public.PFMPS pf 
                                GROUP BY pf.SCHOOLING_ID
                          ) pf on pf.SCHOOLING_ID = sco.id
                join (
                                select SCO.STUDENT_ID,count(*) NB_SCO
                                from public.SCHOOLINGS sco
                                GROUP BY SCO.STUDENT_ID
                                HAVING count(*)>1
                     ) s on s.student_id = sco.student_id
           ) pf
        where end_date is not null --scolarité fermée
        and nb_pfmp= 0 -- sans pfmp
        and rang != nb_sco --dont la scolarité n'est pas la derniere en date
        and uai = '0230019W'
        order by 1,2
)
SELECT * 
FROM SCO_INC;
--DELETE FROM PUBLIC.SCHOOLINGS SCO 
--WHERE SCO.ID IN (SELECT sco_id FROM SCO_INC);

**Comment by pskl** [comment]
Identifié par Mikael: 

Automatiser le renvoi en paiement des pfmps qui étaient bloquées par un manque de DA  et dont la DA a été regénérée.

**Comment by DiffusionAplyPro** [comment]
Renvoi des PFMP bloquées avec le motif d'abrogation si les abrogations ont été faites après le blocage
Renvoi des PFMP bloquées avec le motif de DA manquante dont la DA a été générée après le blocage
Renvoi des PFMP avec rejet bancaire sur le BIC ou l'IBAN est faux si le RIB a été modifié (Test sur nouvel IBAN et différent ou le BIC est différent pas sur la date)
Renvoi des PFMP échouées ou le RIB est black listé et dont le RIB a été modifié après le blocage et que le nouvel IBAN et différent ou le BIC est différent

**Comment by gtournadre** [comment]
**Cas de élèves résidents à l'étranger**
Les demandes de paiement sont bloqués par APLyPro, c'est une demande de l'ASP. Pour contourner il faut : 
- Si le code pays de résidence de l'élève n'est pas 100 ou 9100 alors on envoi à APLyPro : 
   - le code pays de résidence 99100, 
   - le code commune de résidence = code commune de l'établissement
   - le code postal de résidence = code postal de l'établissement

**Comment by pskl** [comment]
Suppression des PFMPs inconsistantes

```
SELECT COUNT(*)
,'pfmpsIds = ['||STRING_AGG(PFMP_ID||'',',')||']
Pfmp.where(id: pfmpsIds).each{| i | i.destroy};' LIST_ID
from (
        select  '->' pf,pf.id pfmp_id,pf.start_date,pf.end_date,pf.day_count
                ,'->' sco,sco.id sco_id,sco.start_date,sco.end_date
                ,'->' pt, pt.to_state,pt.created_at
                ,'Pfmp.find('||pf.id||').destroy' lrb
        from public.PFMPS pf
        join public.SCHOOLINGS sco on  sco.id = pf.SCHOOLING_ID
        join public.STUDENTS s on s.id = sco.STUDENT_ID
        left join public.PFMP_TRANSITIONS pt on pt.PFMP_ID = pf.id and pt.MOST_RECENT = true
        where ( pt.to_state not in ('completed','validated') or pt.id is null)
        and pf.end_date < '2024-01-01'
        and (
                sco.end_date is not null
             or pf.end_date not between coalesce(sco.start_date,'2023-09-04') and coalesce(sco.end_date,'2024-09-01')
            )
       limit 2300
     ) da
```

**Comment by pskl** [comment]
Pour les paiements à l'étranger:
- Quand l'addresse est mise a jour dans FetchSchooling
- Si il y a un paiement bloqué pour cause d'addresse -> relancer

**Comment by pskl** [comment]
A ma connaissance toutes les tâches automatisables ont été traitées.
